name: E2E on Vercel Preview

on:
  repository_dispatch:
    types: [vercel.deployment.success]
  workflow_dispatch:

jobs:
  e2e:
    if: github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npm -w apps/e2e run install:browsers

      - name: Run Playwright against preview URL
        env:
          E2E_BASE_URL: ${{ github.event.client_payload.url || inputs.base_url }}
        run: npm -w apps/e2e test


